"""Update

Revision ID: af58725b8686
Revises: 9207026ed0c1
Create Date: 2023-06-13 21:43:54.266393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af58725b8686'
down_revision = '9207026ed0c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'url')
    op.drop_column('resumes', 'sort_order')
    # ### end Alembic commands ###
